Repository alicevision/popsift, pull requests merged in 2020-05, with the labels that each got.

#89 test whether image fits into CUDA textures
  src/popsift/common/debug_macros.h
  src/popsift/common/device_prop.cu
  src/popsift/common/device_prop.h
  src/popsift/popsift.cpp
  src/popsift/popsift.h
Labels: prio:major, review, type:feature

#92 [cmake] windows fixes
  CMakeLists.txt
  appveyor.yml
  src/CMakeLists.txt
  src/application/CMakeLists.txt
  src/application/main.cpp
  src/popsift/common/assist.h
Labels: scope:build, windows

#87 [docker] update cmake and split docker in 2 parts
  CHANGES.md
  Dockerfile
  Dockerfile_deps
Labels: scope:build

#97 [doc] updated changelog
  CHANGES.md
Labels: scope:doc
