Repository alicevision/popsift, pull requests merged in 2020-04, with the labels that each got.

#72 [cmake] cleaning and preparing release
  .clang-format
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question_help.md
  .github/pull_request_template.md
  .github/stale.yml
  .travis.yml
  CHANGES.md
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  COPYING.md
  README.md
  cmake/Config.cmake.in
  cmake/FindPopsift.cmake
  cmake/sift_config.h.in
  cmake/version.hpp.in
  src/CMakeLists.txt
  src/application/CMakeLists.txt
  src/application/main.cpp
  src/application/match.cpp
  src/popsift/popsift.cpp
  src/popsift/popsift.h
  src/popsift/s_filtergrid.cu
  src/popsift/s_image.cu
  src/popsift/s_orientation.cu
  src/popsift/sift_config.h.in
  src/popsift/sift_desc.cu
  src/popsift/sift_pyramid.cu
  testScripts/CMakeLists.txt
  testScripts/TEST.sh.in
  testScripts/testOxfordDataset.sh.in
Labels: scope:build, type:enhancement

#84 [doc] Update Popart link
  README.md
Labels: bugfix, scope:doc

#75 [cmake] CMake script for choosing CCs
  CMakeLists.txt
  cmake/ChooseCudaCC.cmake
  src/popsift/s_extrema.cu
Labels: cuda, scope:build

#78 [ci] switch to xenial
  .travis.yml
Labels: scope:ci, type:enhancement

#86 Examples on windows
  appveyor.yml
  src/application/pgmread.cpp
Labels: scope:build, windows

#82 Resolve race conditions identified by racecheck.
  src/popsift/common/excl_blk_prefix_sum.h
  src/popsift/s_orientation.cu
Labels: bugfix, type:bug

#81 Remove boost from core popsift library
  .gitignore
  CMakeLists.txt
  README.md
  cmake/Config.cmake.in
  src/CMakeLists.txt
  src/application/CMakeLists.txt
  src/popsift/common/sync_queue.h
  src/popsift/popsift.cpp
  src/popsift/popsift.h
Labels: type:enhancement
