Repository alicevision/popsift, pull requests merged in 2020-02, with the labels that each got.

#67 Fix crashes appearing on CUDA CC 7 cards.
  .travis.yml
  src/popsift/common/warp_bitonic_sort.h
  src/popsift/s_desc_loop.cu
Labels: bugfix, cuda, prio:critical

#65 [cmake] fix for Boost 1.70
  src/application/CMakeLists.txt
  src/application/main.cpp
  src/application/match.cpp
  src/application/pgmread.cpp
Labels: bugfix, scope:build

#71 Improved resource releasing
  src/application/CMakeLists.txt
  src/popsift/popsift.cpp
  src/popsift/popsift.h
Labels: type:enhancement
