Repository alicevision/popsift, pull requests merged in 2025-08, with the labels that each got.

#162 First-order CUDA follow-up fix: do not use NVTX
  CMakeLists.txt
  appveyor.yml
  cmake/sift_config.h.in
  cudaInstallAppveyor.cmd
  src/CMakeLists.txt
  src/application/CMakeLists.txt
  src/popsift/popsift.cu
  src/popsift/popsift.h
  src/popsift/s_filtergrid.cu
  src/popsift/s_image.cu
  src/popsift/s_orientation.cu
  src/popsift/sift_desc.cu
  src/popsift/sift_pyramid.cu
Labels: prio:blocker, type:bug, ready, cuda, bugfix

#167 Adding a VLFeat-compliant feature descriptor
  CHANGES.md
  src/CMakeLists.txt
  src/application/main.cpp
  src/application/match.cpp
  src/popsift/s_desc_vlfeat.cu
  src/popsift/s_desc_vlfeat.h
  src/popsift/s_gradiant.h
  src/popsift/sift_conf.cu
  src/popsift/sift_conf.h
  src/popsift/sift_desc.cu
Labels: type:feature, prio:major, in progress, cuda

#169 fix compile for CUDA 13
  src/popsift/s_extrema.cu
  src/popsift/s_filtergrid.cu
Labels: scope:build, cuda
